name: BILIBILI_HELPER

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '10 1 * * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: set-version
        run: echo "::set-output name=version::$(wget -qO- -t1 -T2 "https://api.github.com/repos/JunzhouLiu/BILIBILI-HELPER/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g;s/V//g')"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache BILIBILI-HELPER Jar
        id: cache-jar
        uses: actions/cache@v2
        with:
          path: ./jar/
          key: ${{ runner.os }}-bilibili-helper-${{ steps.set-version.outputs.version }}
      - name: Download Jar
        if: steps.cache-jar.outputs.cache-hit != 'true'
        run: chmod +x download.sh && bash download.sh
      - name: Run BILIBILI-HELPER
        env:
          BILI_JCT: ${{ secrets.BILI_JCT }}
          DEDEUSERID: ${{ secrets.DEDEUSERID }}
          SESSDATA: ${{ secrets.SESSDATA }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run:
          java -jar ./jar/BILIBILI-HELPER.jar ${DEDEUSERID} ${SESSDATA} ${BILI_JCT} ${SERVERPUSHKEY}
