name: BILIBILI_HELPER

#on:
  #push:
    #branches: main
  #workflow_dispatch:
  #schedule:
    #- cron: '10 1 31 * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时
#name: compile

on:
  workflow_dispatch:
  schedule:
    - cron: '11 9 * * */5'
    - cron: '34 2 * * 2,4,6'
    - cron: '4 12 * * 1,3'
jobs:
  start:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: set-version
        run: echo "::set-output name=version::$(wget -qO- -t1 -T2 "https://api.github.com/repos/JunzhouLiu/BILIBILI-HELPER-PRE/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g;s/V//g')"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache BILIBILI-HELPER Jar
        id: cache-jar
        uses: actions/cache@v2
        with:
          path: ./jar/
          key: ${{ runner.os }}-BILIBILI-HELPER-${{ steps.set-version.outputs.version }}
      - name: Download Jar
        if: steps.cache-jar.outputs.cache-hit != 'true'
        run: chmod +x setup.sh
      - name: Run BILIBILI-HELPER
        env:
#          BCONFIG: ${{ secrets.CONFIG }}
#          DEDEUSERID: ${{ secrets.DEDEUSERID }}
#          SESSDATA: ${{ secrets.SESSDATA }}
#          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run: |
           bash setup.sh
           cd ${HOME}/BILIBILI-HELPER
           java -jar BILIBILI-HELPER.jar config.json
